### ISSUE TITLE
Is it a Open Source Code ?

### ISSUE THREAD

**Issue by mgrange** [chiararuggeri/nrf52-OTA-BLE-Linux#1]
is your code reusable for industial projects?

**Comment by chiararuggeri** [comment]
Yes, it is open source. You can reuse it if you need it

**Comment by mgrange** [comment]
Thanks for your quick answer

**Comment by ayoubnfh** [comment]
Hi, i want to test your code but unfortunately i have this error : 
AttributeError: 'Ui_MainWindow' object has no attribute 'ble_conn'
can you help me with that ?
